export const robots = [
  {
    id: 'robot-ur5e',
    alias: '팔레타이징 로봇',
    location: '1번 라인 · 포장 셀',
    duty: '완제품 상자 적재',
    model: 'UR5e',
    code: 'RB-PKG-01',
    status: 'normal',
    mode: '원격 운전',
    owner: '김작업자 (본인)',
    skill: '상자 팔레타이징',
    progress: 68,
    tool: '진공 그리퍼 VG10',
    gripper: '정상 · 흡착 유지',
    temperature: { level: 'normal', label: '정상', value: '54°C', limit: '80°C' },
    load: { level: 'normal', label: '정상' },
    safety: { eStop: false, protectiveStop: false, guard: false },
    available: true,
    adminStopped: false,
    skills: ['집기', '이동', '놓기', '팔레타이징'],
    currentTask: 'A형 상자 12개 적재',
    lastReceived: '방금 전',
  },
  {
    id: 'robot-fr3',
    alias: '부품 공급 로봇',
    location: '2번 라인 · 조립 셀',
    duty: '조립 부품 공급',
    model: 'FR3-WMS',
    code: 'RB-ASM-02',
    status: 'warning',
    mode: '원격 운전',
    owner: '없음',
    skill: '대기 중',
    progress: 0,
    tool: '2지 평행 그리퍼',
    gripper: '정상 · 열림',
    temperature: { level: 'warning', label: '주의', value: '78°C', limit: '80°C' },
    load: { level: 'normal', label: '정상' },
    safety: { eStop: false, protectiveStop: false, guard: true },
    available: true,
    adminStopped: false,
    skills: ['집기', '이동', '부품 공급'],
    currentTask: '대기 중',
    lastReceived: '0.4초 전',
  },
];

export const alertsSeed = [
  {
    id: 1,
    level: 'warning',
    robotId: 'robot-fr3',
    title: '관절 온도가 주의 기준에 가깝습니다',
    detail: '2번 관절 78°C / 주의 기준 80°C',
    state: '발생',
    assignee: '미지정',
    action: '부하와 냉각 상태를 확인하세요.',
    elapsed: '4분',
  },
  {
    id: 2,
    level: 'task',
    robotId: 'robot-ur5e',
    title: '팔레트 적재 작업이 68% 진행되었습니다',
    detail: '8 / 12 상자 완료',
    state: '발생',
    assignee: '김작업자',
    action: '작업 완료까지 대기하세요.',
    elapsed: '1분',
  },
];

export const historySeed = [
  {
    id: 'CMD-2026-0916-041',
    time: '오늘 14:32:18',
    robotId: 'robot-ur5e',
    robot: '포장 셀 · 팔레타이징 로봇',
    command: 'A형 상자 4개를 출하 팔레트로 옮겨줘',
    requester: '김작업자',
    validation: 'safe',
    execution: 'success',
    input: '음성',
    duration: '1분 42초',
    stopped: false,
  },
  {
    id: 'CMD-2026-0916-038',
    time: '오늘 13:48:06',
    robotId: 'robot-fr3',
    robot: '조립 셀 · 부품 공급 로봇',
    command: '파란 부품을 3번 작업대로 가져다줘',
    requester: '이작업자',
    validation: 'safe',
    execution: 'stop',
    input: '텍스트',
    duration: '38초',
    stopped: true,
  },
  {
    id: 'CMD-2026-0916-035',
    time: '오늘 12:15:42',
    robotId: 'robot-ur5e',
    robot: '포장 셀 · 팔레타이징 로봇',
    command: '상자를 사람 통로 쪽 임시대에 내려놔',
    requester: '김작업자',
    validation: 'blocked',
    execution: 'none',
    input: '음성',
    duration: '12초',
    stopped: false,
  },
  {
    id: 'CMD-2026-0916-031',
    time: '오늘 10:22:10',
    robotId: 'robot-fr3',
    robot: '조립 셀 · 부품 공급 로봇',
    command: '부품 가져다줘',
    requester: '박작업자',
    validation: 'question',
    execution: 'none',
    input: '음성',
    duration: '9초',
    stopped: false,
  },
];

export const services = [
  {
    id: 'planner',
    name: '동작계획 서비스',
    technical: 'PLANNER',
    status: 'warning',
    checked: '14:35:28',
    lastHealthy: '14:31:02',
    duration: '4분 26초',
    issue: '응답이 평소보다 느립니다',
    impact: '새 명령의 동작 준비가 지연될 수 있습니다.',
    action: '진행 중인 작업은 유지됩니다. 반복되면 진단자료를 내보내세요.',
  },
  {
    id: 'ros2',
    name: '로봇 통신',
    technical: 'ROS 2',
    status: 'healthy',
    checked: '14:35:31',
    lastHealthy: '14:35:31',
    duration: '7일 3시간',
    issue: '문제 없음',
    impact: '로봇 상태와 명령이 정상적으로 전달됩니다.',
    action: '조치가 필요하지 않습니다.',
  },
  {
    id: 'safety',
    name: '안전 제어장치',
    technical: 'SAFETY PLC',
    status: 'healthy',
    checked: '14:35:30',
    lastHealthy: '14:35:30',
    duration: '15일 6시간',
    issue: '문제 없음',
    impact: '안전 신호를 정상적으로 수신하고 있습니다.',
    action: '조치가 필요하지 않습니다.',
  },
  {
    id: 'latency',
    name: '통신 응답시간',
    technical: 'LATENCY',
    status: 'healthy',
    checked: '14:35:29',
    lastHealthy: '14:35:29',
    duration: '7일 3시간',
    issue: '평균 42ms · 정상 범위',
    impact: '화면 상태가 정상 속도로 갱신됩니다.',
    action: '조치가 필요하지 않습니다.',
  },
];

export const routinesSeed = [
  { id: 1, name: 'A형 상자 팔레트 적재', command: 'A형 상자를 출하 팔레트 1번 위치부터 차례로 적재', skills: '집기 · 이동 · 놓기', robots: '팔레타이징 로봇', favorite: true },
  { id: 2, name: '조립 부품 공급', command: '파란 부품 트레이를 3번 작업대로 공급', skills: '집기 · 부품 공급', robots: '부품 공급 로봇', favorite: true },
  { id: 3, name: '빈 상자 회수', command: '빈 상자를 회수대에 옮기기', skills: '집기 · 이동 · 놓기', robots: '팔레타이징 로봇', favorite: false },
];

export const usersSeed = [
  { id: 1, name: '김현우', identity: 'kim.hw@factory.local', role: '작업자', assignment: '포장 셀 · 팔레타이징 로봇', status: '활성', lastLogin: '오늘 14:20' },
  { id: 2, name: '이지민', identity: 'lee.jm@factory.local', role: '관리자', assignment: '전체 셀', status: '활성', lastLogin: '오늘 13:58' },
  { id: 3, name: '박서준', identity: 'park.sj@factory.local', role: '안전관리자', assignment: '전체 셀', status: '활성', lastLogin: '어제 17:42' },
  { id: 4, name: '최유진', identity: 'choi.yj@factory.local', role: '작업자', assignment: '조립 셀 · 부품 공급 로봇', status: '비활성', lastLogin: '9월 3일 09:11' },
];
