cmake_minimum_required(VERSION 3.16)
project(forstick2_g1_pd CXX)
set(CMAKE_CXX_STANDARD 17)
find_package(gz-sim REQUIRED)
find_package(gz-plugin REQUIRED COMPONENTS register)
find_package(gz-transport REQUIRED)
find_package(gz-msgs REQUIRED)
add_library(G1PdController SHARED G1PdController.cc)
target_link_libraries(G1PdController PRIVATE gz-sim::gz-sim gz-plugin::register
                      gz-transport::gz-transport gz-msgs::gz-msgs)
